# Spark DataFrames Project Exercise

Let's get some quick practice with your new Spark DataFrame skills, you will be asked some basic questions about some stock market data, in this case Walmart Stock from the years 2012-2017. This exercise will just ask a bunch of questions, unlike the future machine learning exercises, which will be a little looser and be in the form of "Consulting Projects", but more on that later!

For now, just answer the questions and complete the tasks below.

#### Use the walmart_stock.csv file to Answer and complete the  tasks below!

#### Start a simple Spark Session

In [1]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

Starting Spark application

SparkSession available as 'spark'.
/usr/bin/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

#### Load the Walmart Stock CSV File, have Spark infer the data types.

In [3]:
df = spark.read.format('csv').option("inferSchema", True).option("header",True).option("sep",',').load("wasb://sparklab@sparklabhdinstorage.blob.core.windows.net/HdiNotebooks/walmart_stock.csv")

#### What are the column names?

In [4]:
df.columns

['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close']

#### What does the Schema look like?

In [6]:
df.printSchema()

root
 |-- Date: timestamp (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

#### Print out the first 5 columns.

In [9]:
result = df.select('Date', 'Open', 'High', 'Low', 'Close')
result.show()

+-------------------+------------------+------------------+------------------+------------------+
|               Date|              Open|              High|               Low|             Close|
+-------------------+------------------+------------------+------------------+------------------+
|2012-01-03 00:00:00|         59.970001|         61.060001|         59.869999|         60.330002|
|2012-01-04 00:00:00|60.209998999999996|         60.349998|         59.470001|59.709998999999996|
|2012-01-05 00:00:00|         59.349998|         59.619999|         58.369999|         59.419998|
|2012-01-06 00:00:00|         59.419998|         59.450001|         58.869999|              59.0|
|2012-01-09 00:00:00|         59.029999|         59.549999|         58.919998|             59.18|
|2012-01-10 00:00:00|             59.43|59.709998999999996|             58.98|59.040001000000004|
|2012-01-11 00:00:00|         59.060001|         59.529999|59.040001000000004|         59.400002|
|2012-01-12 00:00:00|59.790001000000004|              60.0|         59.400002|              59.5|
|2012-01-13 00:00:00|             59.18|59.610001000000004|59.009997999999996|59.540001000000004|
|2012-01-17 00:00:00|         59.869999|60.110001000000004|             59.52|         59.849998|
|2012-01-18 00:00:00|59.790001000000004|         60.029999|         59.650002|60.009997999999996|
|2012-01-19 00:00:00|             59.93|             60.73|             59.75|60.610001000000004|
|2012-01-20 00:00:00|             60.75|             61.25|         60.669998|61.009997999999996|
|2012-01-23 00:00:00|         60.810001|             60.98|60.509997999999996|             60.91|
|2012-01-24 00:00:00|             60.75|              62.0|             60.75|61.389998999999996|
|2012-01-25 00:00:00|             61.18|61.610001000000004|61.040001000000004|         61.470001|
|2012-01-26 00:00:00|         61.799999|             61.84|             60.77|         60.970001|
|2012-01-27 00:00:00|60.860001000000004|         61.119999|60.540001000000004|60.709998999999996|
|2012-01-30 00:00:00|         60.470001|             61.32|         60.349998|         61.299999|
|2012-01-31 00:00:00|         61.529999|             61.57|         60.580002|61.360001000000004|
+-------------------+------------------+------------------+------------------+------------------+
only showing top 20 rows

#### Use describe() to learn about the DataFrame.

In [11]:
describe_df = df.describe()
describe_df.printSchema()
describe_df.show()

root
 |-- summary: string (nullable = true)
 |-- Open: string (nullable = true)
 |-- High: string (nullable = true)
 |-- Low: string (nullable = true)
 |-- Close: string (nullable = true)
 |-- Volume: string (nullable = true)
 |-- Adj Close: string (nullable = true)

+-------+------------------+-----------------+-----------------+-----------------+-----------------+-----------------+
|summary|              Open|             High|              Low|            Close|           Volume|        Adj Close|
+-------+------------------+-----------------+-----------------+-----------------+-----------------+-----------------+
|  count|              1258|             1258|             1258|             1258|             1258|             1258|
|   mean| 72.35785375357709|72.83938807631165| 71.9186009594594|72.38844998012726|8222093.481717011|67.23883848728146|
| stddev|  6.76809024470826|6.768186808159218|6.744075756255496|6.756859163732991|  4519780.8431556|6.722609449996857|
|    min|56.389998999999996|        57.060001|        56.299999|        56.419998|          2094900|        50.363689|
|    max|         90.800003|        90.970001|            89.25|        90.470001|         80898100|84.91421600000001|
+-------+------------------+-----------------+-----------------+-----------------+-----------------+-----------------+

## Bonus Question!
#### There are too many decimal places for mean and stddev in the describe() dataframe. Format the numbers to just show up to two decimal places. Pay careful attention to the datatypes that .describe() returns, we didn't cover how to do this exact formatting, but we covered something very similar. [Check this link for a hint](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.Column.cast)

If you get stuck on this, don't worry, just view the solutions.

root
 |-- summary: string (nullable = true)
 |-- Open: string (nullable = true)
 |-- High: string (nullable = true)
 |-- Low: string (nullable = true)
 |-- Close: string (nullable = true)
 |-- Volume: string (nullable = true)
 |-- Adj Close: string (nullable = true)

+-------+--------+--------+--------+--------+--------+
|summary|    Open|    High|     Low|   Close|  Volume|
+-------+--------+--------+--------+--------+--------+
|  count|1,258.00|1,258.00|1,258.00|1,258.00|    1258|
|   mean|   72.36|   72.84|   71.92|   72.39| 8222093|
| stddev|    6.77|    6.77|    6.74|    6.76| 4519781|
|    min|   56.39|   57.06|   56.30|   56.42| 2094900|
|    max|   90.80|   90.97|   89.25|   90.47|80898100|
+-------+--------+--------+--------+--------+--------+

#### Create a new dataframe with a column called HV Ratio that is the ratio of the High Price versus volume of stock traded for a day.

In [19]:
df2 = df.withColumn("HV Ratio", col("High")/col("Volume")).select("HV Ratio")
df2.show()

+--------------------+
|            HV Ratio|
+--------------------+
|4.819714653321546E-6|
|6.290848613094555E-6|
|4.669412994783916E-6|
|7.367338463826307E-6|
|8.915604778943901E-6|
|8.644477436914568E-6|
|9.351828421515645E-6|
| 8.29141562102703E-6|
|7.712212102001476E-6|
|7.071764823529412E-6|
|1.015495466386981E-5|
|6.576354146362592...|
| 5.90145296180676E-6|
|8.547679455011844E-6|
|8.420709512685392E-6|
|1.041448341728929...|
|8.316075414862431E-6|
|9.721183814992126E-6|
|8.029436027707578E-6|
|6.307432259386365E-6|
+--------------------+
only showing top 20 rows

#### What day had the Peak High in Price?

In [22]:
df.orderBy(col('High').desc()).show(1)

+-------------------+---------+---------+-----+---------+-------+---------+
|               Date|     Open|     High|  Low|    Close| Volume|Adj Close|
+-------------------+---------+---------+-----+---------+-------+---------+
|2015-01-13 00:00:00|90.800003|90.970001|88.93|89.309998|8215400|83.825448|
+-------------------+---------+---------+-----+---------+-------+---------+
only showing top 1 row

#### What is the mean of the Close column?

In [23]:
df.select(avg("Close")).show()

+-----------------+
|       avg(Close)|
+-----------------+
|72.38844998012726|
+-----------------+

#### What is the max and min of the Volume column?

In [25]:
df.select(max("Volume"),min("Volume")).show()

+-----------+-----------+
|max(Volume)|min(Volume)|
+-----------+-----------+
|   80898100|    2094900|
+-----------+-----------+

#### How many days was the Close lower than 60 dollars?

In [26]:
df.filter(col('Close') < 60).count()

81

#### What percentage of the time was the High greater than 80 dollars ?
#### In other words, (Number of Days High>80)/(Total Days in the dataset)

In [28]:
df.select(df.filter(col('High')>80).count()/count('Date')*100).show()

+---------------------------+
|((115 / count(Date)) * 100)|
+---------------------------+
|          9.141494435612083|
+---------------------------+

#### What is the Pearson correlation between High and Volume?
#### [Hint](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.DataFrameStatFunctions.corr)

In [110]:
df.stat.corr("High","Volume")

+-------------------+
| corr(High, Volume)|
+-------------------+
|-0.3384326061737161|
+-------------------+

#### What is the max High per year?

In [29]:
df3=df.select(year(col('Date')).alias('Year'),col('High'))
df3.groupBy('Year').max('High').orderBy('Year').show()

+----+---------+
|Year|max(High)|
+----+---------+
|2012|77.599998|
|2013|81.370003|
|2014|88.089996|
|2015|90.970001|
|2016|75.190002|
+----+---------+

#### What is the average Close for each Calendar Month?
#### In other words, across all the years, what is the average Close price for Jan,Feb, Mar, etc... Your result will have a value for each of these months.

In [30]:
df4=df.select(month(col('Date')).alias('Month'),col('Close'))
df4.groupBy('Month').avg('Close').orderBy('Month').show()

+-----+-----------------+
|Month|       avg(Close)|
+-----+-----------------+
|    1|71.44801958415842|
|    2|  71.306804443299|
|    3|71.77794377570092|
|    4|72.97361900952382|
|    5|72.30971688679247|
|    6| 72.4953774245283|
|    7|74.43971943925233|
|    8|73.02981855454546|
|    9|72.18411785294116|
|   10|71.57854545454543|
|   11| 72.1110893069307|
|   12|72.84792478301885|
+-----+-----------------+

# Great Job!